# Home assignment 04: Power method

Today your goal is to implement the Power method of eigenvalues and eigenvectors computation and test it on syntetic data. Details are available at [Wikipedia](https://ru.wikipedia.org/wiki/Степенной_метод).

Please, note, that provided method should be applicable to compute the smallest eigenvalue as well (in absolute values).

Just in case, for eigenvalue $\lambda$ and eigenvector $v$ of matrix $A$ the following equation holds:
$$
Ax = \lambda x
$$

In [45]:
import numpy as np

In [46]:
def get_dominant_eigenvalue_and_eigenvector(data, num_steps):
    """
    data: np.ndarray – symmetric diagonalizable real-valued matrix
    num_steps: int – number of power method steps

    Returns:
    eigenvalue: float – dominant eigenvalue estimation after `num_steps` steps
    eigenvector: np.ndarray – corresponding eigenvector estimation
    """
    ### YOUR CODE HERE
    eigenvector = np.ones(data.shape[0], dtype=float)
    eigenvalue = 0.0
    for i in range(num_steps):
        eigenvector = data.dot(eigenvector) / np.linalg.norm(data.dot(eigenvector))
        eigenvalue = eigenvector.T.dot(data.dot(eigenvector)) / eigenvector.T.dot(eigenvector)
    return float(eigenvalue), eigenvector

In [47]:
def get_eigenvalues_and_eigenvectors_with_numpy(data):
    print(data)
    _eigenvalues, _eigenvectors = np.linalg.eig(data)
    max_index = np.argmax(np.abs(_eigenvalues))
    min_index = np.argmin(np.abs(_eigenvalues))

    _test_pair_a = np.array([_eigenvalues[max_index], _eigenvalues[min_index]])
    _test_pair_b = np.array([_eigenvectors[:, max_index], _eigenvectors[:, min_index]])
    if _test_pair_b[0][0] < 0:
        _test_pair_b[0] *= -1
    if _test_pair_b[1][0] < 0:
        _test_pair_b[1] *= -1

    return _test_pair_a, _test_pair_b

In [48]:
for _ in range(1000):
    size = np.random.choice(np.arange(2, 5))
    data = np.random.randn(size, size)
    data = data.T.dot(data)
    a0, b0 = get_dominant_eigenvalue_and_eigenvector(data, 1000)
    assert (
        type(a0) == float
    ), "Return type for eigenvalue is not Python float (please, note, numpy.float64 is a different type)"
    assert type(b0) == np.ndarray, "Return type for eigenvector is not np.ndarray"

    a1, b1 = get_dominant_eigenvalue_and_eigenvector(np.linalg.inv(data), 1000)
    a1 = 1 / a1

    if b0[0] < 0:
        b0 *= -1
    if b1[0] < 0:
        b1 *= -1

    assert np.allclose(
        data.dot(b0), a0 * b0, atol=1e-3
    ), f"Ax != \\lambda x for the dominant eigenvalue check the solution!\n{data.dot(b0), a0 * b0}"
    assert np.allclose(
        data.dot(b1), a1 * b1, atol=1e-3
    ), f"Ax != \\lambda x for the smallest eigenvalue check the solution!\n{data.dot(b1), a1 * b1}"

    _test_pair_a, _test_pair_b = get_eigenvalues_and_eigenvectors_with_numpy(data)

    assert np.allclose(
        _test_pair_a, np.array([a0, a1]), atol=1e-3
    ), f"Eigenvalues are different from np.linalg.eig!\n{_test_pair_a, np.array([a0, a1])}"
    assert np.allclose(
        _test_pair_b, np.array([b0, b1]), atol=1e-3
    ), f"Eigenvectors are different from np.linalg.eig!\n{_test_pair_b, np.array([b0, b1])}"

print(
    "Seems fine! Copy function `get_dominant_eigenvalue_and_eigenvector` to the .py file and submit your solution to the contest!"
)

[[13.48110193 -0.19346473 -5.03116084]
 [-0.19346473  1.35146226  2.69973227]
 [-5.03116084  2.69973227  8.40859074]]
[[ 0.40687917 -1.61876664]
 [-1.61876664  9.77157609]]
[[ 0.95878834  0.20840674 -0.43756666  1.24576185]
 [ 0.20840674  2.33638026 -1.22360698  0.77795995]
 [-0.43756666 -1.22360698  1.28254204 -2.23302736]
 [ 1.24576185  0.77795995 -2.23302736  5.59446435]]
[[ 3.091245    1.3327477  -1.26172378  0.58703312]
 [ 1.3327477   1.40808277 -2.05537819  1.00105006]
 [-1.26172378 -2.05537819  6.97551188  1.26322394]
 [ 0.58703312  1.00105006  1.26322394  2.98348886]]
[[ 6.86877295 -1.03854489  2.95057316]
 [-1.03854489  2.62991971 -0.73022584]
 [ 2.95057316 -0.73022584  1.31372248]]
[[ 2.2263907  -0.87748472  0.86703432]
 [-0.87748472  1.00563085 -0.11811937]
 [ 0.86703432 -0.11811937  2.46533623]]
[[ 3.4216528   3.11296802 -0.68758384]
 [ 3.11296802  3.57295797 -0.9131107 ]
 [-0.68758384 -0.9131107   3.46328647]]
[[ 4.11850943 -0.66880339 -0.69764413]
 [-0.66880339  5.6586544